# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/contract/storage_contract.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'core/contract/storage_contract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$core/contract/storage_contract.proto\x12\x08protocol\"?\n\x17\x42uyStorageBytesContract\x12\x15\n\rowner_address\x18\x01 \x01(\x0c\x12\r\n\x05\x62ytes\x18\x02 \x01(\x03\":\n\x12\x42uyStorageContract\x12\x15\n\rowner_address\x18\x01 \x01(\x0c\x12\r\n\x05quant\x18\x02 \x01(\x03\"C\n\x13SellStorageContract\x12\x15\n\rowner_address\x18\x01 \x01(\x0c\x12\x15\n\rstorage_bytes\x18\x02 \x01(\x03\"C\n\x17UpdateBrokerageContract\x12\x15\n\rowner_address\x18\x01 \x01(\x0c\x12\x11\n\tbrokerage\x18\x02 \x01(\x05\x42\x45\n\x18org.tron.protos.contractZ)github.com/tronprotocol/grpc-gateway/coreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.contract.storage_contract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030org.tron.protos.contractZ)github.com/tronprotocol/grpc-gateway/core'
  _globals['_BUYSTORAGEBYTESCONTRACT']._serialized_start=50
  _globals['_BUYSTORAGEBYTESCONTRACT']._serialized_end=113
  _globals['_BUYSTORAGECONTRACT']._serialized_start=115
  _globals['_BUYSTORAGECONTRACT']._serialized_end=173
  _globals['_SELLSTORAGECONTRACT']._serialized_start=175
  _globals['_SELLSTORAGECONTRACT']._serialized_end=242
  _globals['_UPDATEBROKERAGECONTRACT']._serialized_start=244
  _globals['_UPDATEBROKERAGECONTRACT']._serialized_end=311
# @@protoc_insertion_point(module_scope)
